stages:
  - obfuscate

obfuscation_pipeline:
  stage: obfuscate
  tags:
    - docker
  image: docker:27
  variables:
    DOCKER_HOST: ""
  script:
    - docker info
    - ./scripts/run_all.sh
  artifacts:
    when: always
    paths:
      - outputs/

