stages:
  - obfuscate

obfuscation_pipeline:
  stage: obfuscate
  tags:
    - psec-vm
  script:
    - docker info
    - ./scripts/run_all.sh
  artifacts:
    when: always
    paths:
      - outputs/

