stages:
  - obfuscate

obfuscation_pipeline:
  stage: obfuscate
  tags:
    - shell
  script:
    - apt install -y docker.io
    - docker info
    - ./scripts/run_all.sh
  artifacts:
    when: always
    paths:
      - outputs/

