FROM psec/base:22.04
ENV DEBIAN_FRONTEND=noninteractive

# Dépendances nécessaires
RUN apt-get update && apt-get install -y \
    build-essential \
    clang \
    cmake \
    ninja-build \
    python3 \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

RUN git clone https://github.com/xoreaxeaxeax/movfuscator.git

WORKDIR /opt/movfuscator

RUN chmod +x build.sh && ./build.sh


ENV PATH="/opt/movfuscator/build:${PATH}"

WORKDIR /work
