FROM psec/base:22.04

COPY vendor/tigress_4.0.11-1_all.deb.zip /tmp/tigress.zip

RUN set -eux; \
    apt-get update && apt-get install -y unzip; \
    unzip /tmp/tigress.zip -d /tmp; \
    dpkg -i /tmp/tigress_4.0.11-1_all.deb; \
    rm -rf /tmp/*

WORKDIR /work

