FROM ubuntu:22.04

RUN dpkg --add-architecture i386 && \
    apt update && apt install -y \
    build-essential \
    git \
    clang \
    llvm \
    cmake \
    python3 \
    libc6-dev-i386 \
    gcc-multilib \
    bison \
    wget

WORKDIR /opt
RUN git clone https://github.com/xoreaxeaxeax/movfuscator.git

WORKDIR /opt/movfuscator

RUN chmod +x build.sh install.sh && \
    ./build.sh

ENV PATH="/opt/movfuscator/build:${PATH}"

